### ISSUE TITLE
Incorrect namespaces

### ISSUE THREAD

**Issue by oliverkill** [lkallas/estonianpin#2]
Attempting the included example fails:

![screen](https://user-images.githubusercontent.com/54833578/104014404-a1c97200-51bb-11eb-85cc-05bf2314a07d.PNG)

Using composer v1.x it is possible to bypass the errors by using `composer dumpautoload -o`:

![composer1](https://user-images.githubusercontent.com/54833578/104014562-e94ffe00-51bb-11eb-820b-edb81f7f1afe.PNG)

However it is not possible to bypass the errors with composer v2.x:

![composer2](https://user-images.githubusercontent.com/54833578/104014594-f7058380-51bb-11eb-9724-bf31eb2738cc.PNG)

The reason is that composer v2 deprecates support for incorrect namespaces:
[Using Composer 2.0 with PSR4](https://medium.com/legacybeta/using-composer-2-0-with-psr4-388b78b98aaa)

**Comment by lkallas** [comment]
@oliverkill haven't tested it myself, so asking is the `composer v2 support` backward compatible with composer v1?
Feel free to open a PR with the fix. Also bump the version if you're at it.

**Comment by oliverkill** [comment]
Yes, it does work with composer v1. Created [PR](https://github.com/lkallas/estonianpin/pull/3) and bumped version as well.
